# Generated by Django 4.0 on 2021-12-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='mealId',
            new_name='post',
        ),
    ]
