# Generated by Django 4.0 on 2021-12-21 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('comments', '0001_initial'),
        ('replies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Replies',
        ),
    ]
