# Generated by Django 4.0 on 2021-12-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='recipe',
            field=models.IntegerField(),
        ),
    ]
