# Generated by Django 4.0 on 2021-12-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_meal_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='datetime',
            field=models.DateField(),
        ),
    ]
