# Generated by Django 4.0 on 2021-12-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_rename_datetime_meal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='recipe',
            field=models.URLField(max_length=45),
        ),
    ]
